PACKAGE_NAME="reform2_lpc"
PACKAGE_VERSION="1.68"
BUILT_MODULE_NAME[0]="reform2_lpc"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_CONFIG="CONFIG_SPI_MASTER"
# struct spi_device changed API in v5.18
BUILD_EXCLUSIVE_KERNEL_MIN="5.18"
