PACKAGE_NAME="ezurio-qcacld-2.0"
PACKAGE_VERSION="1.0.0"

# CONFIG_64BIT: __udivdi3 is only available on 64bit arches
BUILD_EXCLUSIVE_CONFIG="CONFIG_64BIT CONFIG_WIRELESS"

BUILT_MODULE_NAME[0]="qcacld2"
DEST_MODULE_NAME[0]="qcacld2"
DEST_MODULE_LOCATION[0]="/kernel/drivers/staging/qcacld-2.0" # from upstream Kbuild
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules WLAN_ROOT=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build MODNAME=qcacld2 CONFIG_QCA_WIFI_ISOC=0 CONFIG_QCA_WIFI_2_0=1 CONFIG_QCA_CLD_WLAN=m WLAN_OPEN_SOURCE=1 CONFIG_CLD_HL_SDIO_CORE=y CONFIG_FORCE_MLO_SUPPORT=y CONFIG_SUPPORT_P2P_BY_ONE_INTF_WLAN=y"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL_MIN="6.7"                             # needs cfg80211_ap_update from bb55441c (v6.7-rc1)
